name: CI
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: unit-test
      run: |
        export TUSHARE_TOKEN=${{ secrets.TUSHARE_TOKEN }}
        docker-compose up --exit-code-from bazel
# mkdir -p /home/runner/BAZEL_USER_ROOT
# export BAZEL_USER_ROOT=/home/runner/BAZEL_USER_ROOT
# mkdir -p /home/runner/OUTPUT_DIR
# export OUTPUT_DIR=/home/runner/OUTPUT_DIR
