name: CI
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: unit-test
      env:
        BAZEL_USER_ROOT: /home/runner/BAZEL_USER_ROOT
        OUTPUT_DIR: /home/runner/OUTPUT_DIR
      run: |
        export TUSHARE_TOKEN=${{ secrets.TUSHARE_TOKEN }}
        mkdir -p /home/runner/BAZEL_USER_ROOT
        mkdir -p /home/runner/OUTPUT_DIR
        docker-compose up --exit-code-from bazel
